set_property PACKAGE_PIN P14 [get_ports TMP3_out_scl_io]
set_property PACKAGE_PIN R14 [get_ports TMP3_out_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports TMP3_out_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports TMP3_out_sda_io]
set_property PACKAGE_PIN T11 [get_ports uart_rtl_rxd]
set_property PACKAGE_PIN W15 [get_ports uart_rtl_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]
